services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  NITSAN\NsCourses\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
   
  NITSAN\NsCourses\Event\EventListener:  
    tags:
      - name: event.listener
        identifier: 'ns_faq/extension-activated'

  
  NITSAN\NsCourses\Event\CourseCreatedEventListener:
    autowire: true
    autoconfigure: true
    public: true




  # NITSAN\NsCourses\Event\CourseCreatedEvent:  
  #   tags:
  #     - name: event.listener
  #       identifier: 'ns_courses/course-created-listener'